updated brew and osx defaults, added node script, removed unused colors, pruned css snippets, enabled relative numbers

diff --git a/lib/brew b/lib/brew
--- a/lib/brew
+++ b/lib/brew
@@ -1,29 +1,56 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-# Make sure we’re using the latest Homebrew
-brew update
+run_brew() {
 
-# Upgrade any already-installed formulae
-brew upgrade
+    # Check for Homebrew
+    if type_exists 'brew'; then
+        e_header "Updating Homebrew..."
+        # Use the latest version of Homebrew
+        brew update
+        [[ $? ]] && e_success "Done"
 
-# Install GNU core utilities (those that come with OS X are outdated)
-# brew install coreutils
-# echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
-# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
-# brew install findutils
-# Install Bash 4
-# brew install bash
+        e_header "Updating any existing Homebrew formulae..."
+        # Upgrade any already-installed formulae
+        brew upgrade
+        [[ $? ]] && e_success "Done"
 
-# Install wget with IRI support
-brew install wget --enable-iri
+        e_header "Checking status of desired Homebrew formulae..."
+        local list_formulae
+        local -a missing_formulae
+        local -a desired_formulae=(
+            'git'
+            'ack'
+            'node'
+            'git-ftp'
+            'heroku-toolbelt'
+        )
 
-# Install other useful binaries
-brew install ack
-# brew install imagemagick
-brew install node
-brew install rename
-brew install webkit2png
-brew install git-ftp
+        for index in ${!desired_formulae[*]}
+        do
+            if ! formula_exists ${desired_formulae[$index]}; then
+                # Store the name (and options) of every missing formula
+                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
+            fi
+        done
 
-# Remove outdated versions from the cellar
-brew cleanup
+        if [[ "$missing_formulae" ]]; then
+            # Convert the array of missing formula into a list of space-separate strings
+            list_formulae=$( printf "%s " "${missing_formulae[@]}" )
+
+            e_header "Installing missing Homebrew formulae..."
+            # Install all missing formulae
+            brew install $list_formulae
+
+            [[ $? ]] && e_success "Done"
+        fi
+
+        # Remove outdated versions from the Cellar
+        brew cleanup
+    else
+        printf "\n"
+        e_error "Error: Homebrew not found."
+        printf "Aborting...\n"
+        exit
+    fi
+
+}
