Lots of cleanup, single quotes, ui edits, updating install scripts

diff --git a/lib/brew b/lib/brew
--- a/lib/brew
+++ b/lib/brew
@@ -1,62 +1,61 @@
 #!/bin/zsh
 
-run_brew() {
-  # Check for Homebrew
-  if type_exists 'brew'; then
-    e_header "Updating Homebrew..."
-    # Use the latest version of Homebrew
-    brew update
-    [[ $? ]] && e_success "Done"
+# Check for Homebrew
+if type_exists 'brew'; then
+  e_header "Updating Homebrew..."
+  # Use the latest version of Homebrew
+  brew update
+  [[ $? ]] && e_success "Done"
 
-    e_header "Updating any existing Homebrew formulae..."
-    # Upgrade any already-installed formulae
-    brew upgrade
-    [[ $? ]] && e_success "Done"
+  e_header "Updating any existing Homebrew formulae..."
+  # Upgrade any already-installed formulae
+  brew upgrade
+  [[ $? ]] && e_success "Done"
 
-    # Specify brew formulae, git is installed first in install.sh before this runs
-    e_header "Checking status of desired Homebrew formulae..."
-    local list_formulae
-    local -a missing_formulae
-    local -a desired_formulae=(
-      'ack'
-      'asdf'
-      'bat'
-      'btop'
-      'fd'
-      'ffmpeg'
-      'luarocks'
-      'just'
-      'markdown'
-      'neovim'
-      'par'
-      'ripgrep'
-    )
+  # Specify brew formulae, git is installed first in install.sh before this runs
+  e_header "Checking status of desired Homebrew formulae..."
+  local list_formulae
+  local -a missing_formulae
+  local -a desired_formulae=(
+    'ack'
+    'asdf'
+    'bat'
+    'btop'
+    'fd'
+    'ffmpeg'
+    'lua-language-server'
+    'luarocks'
+    'just'
+    'markdown'
+    'neovim'
+    'par'
+    'ripgrep'
+  )
 
-    for index in ${!desired_formulae[*]}
-    do
-      if ! formula_exists ${desired_formulae[$index]}; then
-        # Store the name (and options) of every missing formula
-        missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
-      fi
-    done
-
-    if [[ "$missing_formulae" ]]; then
-      # Convert the array of missing formula into a list of space-separate strings
-      list_formulae=$( printf "%s " "${missing_formulae[@]}" )
-
-      e_header "Installing missing Homebrew formulae..."
-      # Install all missing formulae
-      brew install $list_formulae
-
-      [[ $? ]] && e_success "Done"
+  for index in ${!desired_formulae[*]}
+  do
+    if ! formula_exists ${desired_formulae[$index]}; then
+      # Store the name (and options) of every missing formula
+      missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
     fi
+  done
 
-    # Remove outdated versions from the Cellar
-    brew cleanup
-  else
-    printf "\n"
-    e_error "Error: Homebrew not found."
-    printf "Aborting...\n"
-    exit
+  if [[ "$missing_formulae" ]]; then
+    # Convert the array of missing formula into a list of space-separate strings
+    list_formulae=$( printf "%s " "${missing_formulae[@]}" )
+
+    e_header "Installing missing Homebrew formulae..."
+    # Install all missing formulae
+    brew install $list_formulae
+
+    [[ $? ]] && e_success "Done"
+  fi
+
+  # Remove outdated versions from the Cellar
+  brew cleanup
+else
+  printf "\n"
+  e_error "Error: Homebrew not found."
+  printf "Aborting...\n"
+  exit
 fi
-}
