beginning lua transfer for nvim, nvim as diff tool, remove old snippets

diff --git a/lib/npm b/lib/npm
--- a/lib/npm
+++ b/lib/npm
@@ -1,24 +1,29 @@
 #!/bin/zsh
 
-run_npm() {
+source ./lib/utils
 
-    # Check for npm
-    if type_exists 'npm'; then
-        e_header "Installing Node.js packages..."
+# Check for npm - CURRENTLY BROKEN? not sure why, so we bypass the check
+# if type_exists 'npm'; then
+	e_header "Installing Node.js packages..."
 
-        # List of npm packages
-		# Many of these are LSPs for use with nvim
-        local packages="stylelint-lsp svelte-language-server @tailwindcss/language-server tiddlywiki typescript-language-server vscode-langservers-extracted"
+	# List of npm packages
+	# Many of these are LSPs for use with nvim
+	local packages=(
+		'stylelint-lsp' 
+		'svelte-language-server' 
+		'@tailwindcss/language-server' 
+		'tiddlywiki' 
+		'typescript-language-server' 
+		'vscode-langservers-extracted'
+	)
 
-        # Install packages globally and quietly
-        npm install $packages --global --quiet
+	# Install packages globally and quietly
+	npm install $packages --global --quiet
 
-        [[ $? ]] && e_success "Done"
-    else
-        printf "\n"
-        e_error "Error: npm not found."
-        printf "Aborting...\n"
-        exit
-    fi
-
-}
+	[[ $? ]] && e_success "Done"
+# else
+# 	printf "\n"
+# 	e_error "Error: npm not found."
+# 	printf "Aborting...\n"
+# 	exit
+# fi
